//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailsShopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public int id_customer { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public string email { get; set; }
        public string phone_num { get; set; }
        public System.DateTime date { get; set; }
    }
}
