//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailsShopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procedures
    {
        public int id_procedure { get; set; }
        public string procedure_name { get; set; }
        public string procedure_type { get; set; }
        public Nullable<double> procedure_price { get; set; }
    }
}
